// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// AuditLog varligini temsil eder.
/// </summary>
public class AuditLog
{
    /// <summary>
    /// Denetim kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Islemi gerceklestiren kullanicinin kimligi.
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// Gerceklesen islemin adi (orn. LOGIN, PASSWORD_CHANGED).
    /// </summary>
    public string Action { get; set; } = string.Empty;

    /// <summary>
    /// Islemin ilgili oldugu varlik adi.
    /// </summary>
    public string Entity { get; set; } = string.Empty;

    /// <summary>
    /// Islemin ilgili oldugu varlik kimligi.
    /// </summary>
    public Guid? EntityId { get; set; }

    /// <summary>
    /// Islemin gerceklestigi IP adresi.
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// Islemin gerceklestigi istemci bilgisi (user agent).
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>
    /// Isleme dair ek verilerin JSON formatinda tutuldugu alan.
    /// </summary>
    public string? MetadataJson { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
