// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// BodyMeasurement varligini temsil eder.
/// </summary>
public class BodyMeasurement
{
    /// <summary>
    /// Vucut olcum kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Olcumun ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Olcumun alindigi tarih.
    /// </summary>
    public DateTime RecordedAt { get; set; }

    /// <summary>
    /// Vucut agirligi (kilogram).
    /// </summary>
    public decimal? WeightKg { get; set; }

    /// <summary>
    /// Vucut yag orani (yuzde).
    /// </summary>
    public decimal? BodyFatPercentage { get; set; }

    /// <summary>
    /// Vucut kitle indeksi.
    /// </summary>
    public decimal? BMI { get; set; }

    /// <summary>
    /// Gogus cevresi (santimetre).
    /// </summary>
    public decimal? ChestCm { get; set; }

    /// <summary>
    /// Bel cevresi (santimetre).
    /// </summary>
    public decimal? WaistCm { get; set; }

    /// <summary>
    /// Kalca cevresi (santimetre).
    /// </summary>
    public decimal? HipCm { get; set; }

    /// <summary>
    /// Kol cevresi (santimetre).
    /// </summary>
    public decimal? ArmCm { get; set; }

    /// <summary>
    /// Uyluk cevresi (santimetre).
    /// </summary>
    public decimal? ThighCm { get; set; }
}
