// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Equipment varligini temsil eder.
/// </summary>
public class Equipment
{
    /// <summary>
    /// Ekipmanin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Ekipmanin adi (orn. Dambil, Halter).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Ekipmanin URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;
}
