// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// ExternalLogin varligini temsil eder.
/// </summary>
public class ExternalLogin
{
    /// <summary>
    /// Harici giris kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Girisin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Harici giris saglayicisi (orn. Apple, Google).
    /// </summary>
    public string Provider { get; set; } = string.Empty;

    /// <summary>
    /// Saglayici tarafindaki kullanici kimligi.
    /// </summary>
    public string ProviderUserId { get; set; } = string.Empty;

    /// <summary>
    /// Saglayicidan alinan e-posta adresi.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
