// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// ExternalLogin varligini temsil eder.
/// </summary>
public class ExternalLogin : BaseEntity
{
    /// <summary>
    /// Girisin ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Harici giris saglayicisi (orn. Apple, Google).
    /// </summary>
    public string Provider { get; set; } = string.Empty;

    /// <summary>
    /// Saglayici tarafindaki kullanici kimligi.
    /// </summary>
    public string ProviderUserId { get; set; } = string.Empty;

    /// <summary>
    /// Saglayicidan alinan e-posta adresi.
    /// </summary>
    public string? Email { get; set; }
}
