// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// FAQ varligini temsil eder.
/// </summary>
public class FAQ : BaseEntity
{
    /// <summary>
    /// Iliskili SSS kategorisinin kimligi.
    /// </summary>
    public long CategoryId { get; set; }

    /// <summary>
    /// Sorulan soru metni.
    /// </summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>
    /// Soruya verilen cevap metni.
    /// </summary>
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// Sorunun kategori icindeki listelenme sirasi.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Sorunun aktif/yayinda olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
