// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Feature varligini temsil eder.
/// </summary>
public class Feature
{
    /// <summary>
    /// Ozelligin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Ozelligin sistemsel kodu (orn. AI_WORKOUT).
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Ozelligin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Ozelligin aciklamasi.
    /// </summary>
    public string? Description { get; set; }
}
