// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// GoalHistory varligini temsil eder.
/// </summary>
public class GoalHistory
{
    /// <summary>
    /// Hedef gecmisi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Hedefi degistiren kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Degisiklikten onceki hedef.
    /// </summary>
    public FitnessGoal OldGoal { get; set; }

    /// <summary>
    /// Degisiklikten sonraki hedef.
    /// </summary>
    public FitnessGoal NewGoal { get; set; }

    /// <summary>
    /// Hedefin degistirildigi tarih.
    /// </summary>
    public DateTime ChangedAt { get; set; }

    /// <summary>
    /// Hedef degisikliginin nedeni.
    /// </summary>
    public string? Reason { get; set; }
}
