// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// LeaderboardEntry varligini temsil eder.
/// </summary>
public class LeaderboardEntry
{
    /// <summary>
    /// Liderlik tablosu kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili donemin kimligi.
    /// </summary>
    public Guid LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Siralamadaki kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kullanicinin bu donemde topladigi puan.
    /// </summary>
    public decimal Points { get; set; }

    /// <summary>
    /// Kullanicinin bu donemde tamamladigi antrenman sayisi.
    /// </summary>
    public int WorkoutCount { get; set; }

    /// <summary>
    /// Kullanicinin donem icindeki sirasi.
    /// </summary>
    public int Rank { get; set; }
}
