// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// LeaderboardReward varligini temsil eder.
/// </summary>
public class LeaderboardReward
{
    /// <summary>
    /// Liderlik odulu kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili donemin kimligi.
    /// </summary>
    public Guid LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Odulun verildigi siralama araligi.
    /// </summary>
    public int Rank { get; set; }

    /// <summary>
    /// Verilecek odulun kimligi.
    /// </summary>
    public Guid RewardId { get; set; }
}
