// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// LeaderboardReward varligini temsil eder.
/// </summary>
public class LeaderboardReward : BaseEntity
{
    /// <summary>
    /// Iliskili donemin kimligi.
    /// </summary>
    public long LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Odulun verildigi siralama araligi.
    /// </summary>
    public int Rank { get; set; }

    /// <summary>
    /// Verilecek odulun kimligi.
    /// </summary>
    public long RewardId { get; set; }
}
