// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// LeaderboardEntry varligini temsil eder.
/// </summary>
public class LeaderboardEntry : BaseEntity
{
    /// <summary>
    /// Iliskili donemin kimligi.
    /// </summary>
    public long LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Siralamadaki kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kullanicinin bu donemde topladigi puan.
    /// </summary>
    public decimal Points { get; set; }

    /// <summary>
    /// Kullanicinin bu donemde tamamladigi antrenman sayisi.
    /// </summary>
    public int WorkoutCount { get; set; }

    /// <summary>
    /// Kullanicinin donem icindeki sirasi.
    /// </summary>
    public int Rank { get; set; }
}
