// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;
using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// LeaderboardPeriod varligini temsil eder.
/// </summary>
public class LeaderboardPeriod : BaseEntity
{
    /// <summary>
    /// Donemin turu (haftalik, aylik, tum zamanlar).
    /// </summary>
    public LeaderboardPeriodType Type { get; set; }

    /// <summary>
    /// Donemin baslangic tarihi.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Donemin bitis tarihi.
    /// </summary>
    public DateTime EndDate { get; set; }

    /// <summary>
    /// Donemin guncel/aktif donem olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }
}
