// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Meal varligini temsil eder.
/// </summary>
public class Meal
{
    /// <summary>
    /// Ogun kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Ogunu kaydeden kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Ogunun tuketildigi tarih.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Ogunun turu (kahvalti, ogle, aksam, ara ogun).
    /// </summary>
    public MealType MealType { get; set; }

    /// <summary>
    /// Oguna ait notlar.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
