// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// MerfitScoreBreakdown varligini temsil eder.
/// </summary>
public class MerfitScoreBreakdown
{
    /// <summary>
    /// Skor kirilim kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili Merfit skorunun kimligi.
    /// </summary>
    public Guid MerfitScoreId { get; set; }

    /// <summary>
    /// Skor kaleminin kategorisi (orn. Consistency, Workouts).
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Bu kategoriden kazanilan puan.
    /// </summary>
    public decimal Points { get; set; }
}
