// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// MerfitScore varligini temsil eder.
/// </summary>
public class MerfitScore
{
    /// <summary>
    /// Merfit skoru kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Skorun ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Hesaplanan toplam skor degeri.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Skorun hesaplandigi donemi ifade eden deger.
    /// </summary>
    public string Period { get; set; } = string.Empty;

    /// <summary>
    /// Skorun hesaplandigi tarih.
    /// </summary>
    public DateTime CalculatedAt { get; set; }
}
