// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// MerfitScoreHistory varligini temsil eder.
/// </summary>
public class MerfitScoreHistory : BaseEntity
{
    /// <summary>
    /// Skorun ait oldugu kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Kaydedilen skor degeri.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Skorun kaydedildigi tarih.
    /// </summary>
    public DateTime RecordedAt { get; set; }
}
