// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// MerfitScoreHistory varligini temsil eder.
/// </summary>
public class MerfitScoreHistory
{
    /// <summary>
    /// Skor gecmisi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Skorun ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kaydedilen skor degeri.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Skorun kaydedildigi tarih.
    /// </summary>
    public DateTime RecordedAt { get; set; }
}
