// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// MuscleGroup varligini temsil eder.
/// </summary>
public class MuscleGroup : BaseEntity
{
    /// <summary>
    /// Kas grubunun adi (orn. Gogus, Sirt).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Kas grubunun URL dostu kisa adi.
    /// </summary>
    public string Slug { get; set; } = string.Empty;
}
