// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;
using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Notification varligini temsil eder.
/// </summary>
public class Notification : BaseEntity
{
    /// <summary>
    /// Bildirimin gonderildigi kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Bildirimin turu.
    /// </summary>
    public NotificationType Type { get; set; }

    /// <summary>
    /// Bildirimin basligi.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Bildirimin icerik metni.
    /// </summary>
    public string Body { get; set; } = string.Empty;

    /// <summary>
    /// Bildirime ait ek verilerin JSON formatinda tutuldugu alan.
    /// </summary>
    public string? DataJson { get; set; }

    /// <summary>
    /// Bildirimde gosterilen gorselin adresi.
    /// </summary>
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Bildirimin okunup okunmadigi.
    /// </summary>
    public bool IsRead { get; set; }

    /// <summary>
    /// Bildirimin okundugu tarih.
    /// </summary>
    public DateTime? ReadAt { get; set; }

    /// <summary>
    /// Bildirimin son gecerlilik tarihi.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }
}
