// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// NutritionGoal varligini temsil eder.
/// </summary>
public class NutritionGoal
{
    /// <summary>
    /// Beslenme hedefi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Hedefin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Gunluk hedeflenen kalori miktari.
    /// </summary>
    public decimal DailyCalories { get; set; }

    /// <summary>
    /// Gunluk hedeflenen protein miktari (gram).
    /// </summary>
    public decimal ProteinTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen karbonhidrat miktari (gram).
    /// </summary>
    public decimal CarbsTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen yag miktari (gram).
    /// </summary>
    public decimal FatTarget { get; set; }

    /// <summary>
    /// Gunluk hedeflenen su miktari (mililitre).
    /// </summary>
    public decimal WaterTargetMl { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
