// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// PersonalRecord varligini temsil eder.
/// </summary>
public class PersonalRecord
{
    /// <summary>
    /// Kisisel rekor kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Rekoru kiran kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Rekorun ait oldugu egzersizin kimligi.
    /// </summary>
    public Guid ExerciseId { get; set; }

    /// <summary>
    /// Rekor sirasinda kaldirilan agirlik (kilogram).
    /// </summary>
    public decimal WeightKg { get; set; }

    /// <summary>
    /// Rekor sirasinda yapilan tekrar sayisi.
    /// </summary>
    public int Reps { get; set; }

    /// <summary>
    /// Hesaplanan tahmini bir tekrar maksimumu (1RM).
    /// </summary>
    public decimal EstimatedOneRepMax { get; set; }

    /// <summary>
    /// Rekorun kirildigi tarih.
    /// </summary>
    public DateTime AchievedAt { get; set; }

    /// <summary>
    /// Rekorun kirildigi antrenman oturumunun kimligi.
    /// </summary>
    public Guid? WorkoutSessionId { get; set; }
}
