// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Subscription varligini temsil eder.
/// </summary>
public class Subscription
{
    /// <summary>
    /// Abonelik kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Abonelik sahibi kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Satin alinan abonelik urununun kimligi.
    /// </summary>
    public Guid SubscriptionProductId { get; set; }

    /// <summary>
    /// Odemenin gerceklestigi magaza saglayicisi.
    /// </summary>
    public SubscriptionProvider Provider { get; set; }

    /// <summary>
    /// Magaza tarafindaki islem kimligi.
    /// </summary>
    public string? ExternalTransactionId { get; set; }

    /// <summary>
    /// Abonelik durumu.
    /// </summary>
    public SubscriptionStatus Status { get; set; }

    /// <summary>
    /// Aboneligin baslangic tarihi.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Aboneligin son gecerlilik tarihi.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// Aboneligin otomatik yenilenip yenilenmeyecegi.
    /// </summary>
    public bool AutoRenew { get; set; }

    /// <summary>
    /// Aboneligin iptal edildigi tarih.
    /// </summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
