// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// SubscriptionPlanFeature varligini temsil eder.
/// </summary>
public class SubscriptionPlanFeature
{
    /// <summary>
    /// Iliskili abonelik urununun kimligi.
    /// </summary>
    public Guid SubscriptionProductId { get; set; }

    /// <summary>
    /// Iliskili ozelligin kimligi.
    /// </summary>
    public Guid FeatureId { get; set; }
}
