// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// SupportTicket varligini temsil eder.
/// </summary>
public class SupportTicket
{
    /// <summary>
    /// Destek talebinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Talebi olusturan kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Talebin konusu.
    /// </summary>
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Talebin ilk mesaj icerigi.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Talebin guncel durumu.
    /// </summary>
    public SupportTicketStatus Status { get; set; }

    /// <summary>
    /// Talebin oncelik seviyesi.
    /// </summary>
    public SupportTicketPriority Priority { get; set; }

    /// <summary>
    /// Talebin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Talebin kapatilma tarihi.
    /// </summary>
    public DateTime? ClosedAt { get; set; }
}
