// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// SupportTicketMessage varligini temsil eder.
/// </summary>
public class SupportTicketMessage : BaseEntity
{
    /// <summary>
    /// Iliskili destek talebinin kimligi.
    /// </summary>
    public long TicketId { get; set; }

    /// <summary>
    /// Mesaji gonderen kullanicinin kimligi.
    /// </summary>
    public long SenderUserId { get; set; }

    /// <summary>
    /// Mesaj icerigi.
    /// </summary>
    public string Message { get; set; } = string.Empty;
}
