// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;
using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// SupportTicket varligini temsil eder.
/// </summary>
public class SupportTicket : BaseEntity
{
    /// <summary>
    /// Talebi olusturan kullanicinin kimligi.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Talebin konusu.
    /// </summary>
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Talebin ilk mesaj icerigi.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Talebin guncel durumu.
    /// </summary>
    public SupportTicketStatus Status { get; set; }

    /// <summary>
    /// Talebin oncelik seviyesi.
    /// </summary>
    public SupportTicketPriority Priority { get; set; }

    /// <summary>
    /// Talebin kapatilma tarihi.
    /// </summary>
    public DateTime? ClosedAt { get; set; }
}
