// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// Translation varligini temsil eder.
/// </summary>
public class Translation
{
    /// <summary>
    /// Ceviri kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili dilin kimligi.
    /// </summary>
    public Guid LanguageId { get; set; }

    /// <summary>
    /// Ceviri metnine karsilik gelen anahtar (orn. workout.start).
    /// </summary>
    public string ResourceKey { get; set; } = string.Empty;

    /// <summary>
    /// Anahtara karsilik gelen cevrilmis metin.
    /// </summary>
    public string Value { get; set; } = string.Empty;
}
