// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserReward varligini temsil eder.
/// </summary>
public class UserReward
{
    /// <summary>
    /// Kullanici odulu kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Odulu kazanan kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kazanilan odulun kimligi.
    /// </summary>
    public Guid RewardId { get; set; }

    /// <summary>
    /// Odulun kazanildigi liderlik donemi kimligi.
    /// </summary>
    public Guid? LeaderboardPeriodId { get; set; }

    /// <summary>
    /// Odulun kazanildigi sirlama.
    /// </summary>
    public int? Rank { get; set; }

    /// <summary>
    /// Odulun guncel durumu.
    /// </summary>
    public UserRewardStatus Status { get; set; }

    /// <summary>
    /// Odulun teslim alindigi tarih.
    /// </summary>
    public DateTime? ClaimedAt { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
