// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserGoal varligini temsil eder.
/// </summary>
public class UserGoal
{
    /// <summary>
    /// Kullanici hedefi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Hedefin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Hedefin turu.
    /// </summary>
    public FitnessGoal GoalType { get; set; }

    /// <summary>
    /// Hedef baslangicindaki kilo (kilogram).
    /// </summary>
    public decimal? StartingWeightKg { get; set; }

    /// <summary>
    /// Hedef surecindeki guncel kilo (kilogram).
    /// </summary>
    public decimal? CurrentWeightKg { get; set; }

    /// <summary>
    /// Hedeflenen kilo (kilogram).
    /// </summary>
    public decimal? TargetWeightKg { get; set; }

    /// <summary>
    /// Hedefe ulasilmasi planlanan tarih.
    /// </summary>
    public DateTime? TargetDate { get; set; }

    /// <summary>
    /// Hedefe ulasma yuzdesi.
    /// </summary>
    public decimal? ProgressPercent { get; set; }

    /// <summary>
    /// Hedefin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Hedefin tamamlanma tarihi.
    /// </summary>
    public DateTime? CompletedAt { get; set; }
}
