// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserNotificationSetting varligini temsil eder.
/// </summary>
public class UserNotificationSetting
{
    /// <summary>
    /// Bildirim ayari kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Ayarin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Antrenman hatirlatma bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool WorkoutReminders { get; set; }

    /// <summary>
    /// Gunluk hedef hatirlatma bildiriminin acik olup olmadigi.
    /// </summary>
    public bool DailyGoalReminder { get; set; }

    /// <summary>
    /// Seri (streak) hatirlatma bildiriminin acik olup olmadigi.
    /// </summary>
    public bool StreakReminder { get; set; }

    /// <summary>
    /// Ilerleme guncelleme bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool ProgressUpdates { get; set; }

    /// <summary>
    /// Liderlik tablosu bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool LeaderboardUpdates { get; set; }

    /// <summary>
    /// Urun guncelleme bildirimlerinin acik olup olmadigi.
    /// </summary>
    public bool ProductUpdates { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
