// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserPrivacySetting varligini temsil eder.
/// </summary>
public class UserPrivacySetting
{
    /// <summary>
    /// Gizlilik ayari kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Ayarin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Profilin liderlik tablosunda gorunur olup olmadigi.
    /// </summary>
    public bool ProfileVisibleOnLeaderboard { get; set; }

    /// <summary>
    /// Antrenman istatistiklerinin paylasilip paylasilmadigi.
    /// </summary>
    public bool ShareWorkoutStatistics { get; set; }

    /// <summary>
    /// Kisisellestirilmis onerilerin acik olup olmadigi.
    /// </summary>
    public bool PersonalizedRecommendations { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
