// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserPreference varligini temsil eder.
/// </summary>
public class UserPreference
{
    /// <summary>
    /// Tercih kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Tercihin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi uygulama dili.
    /// </summary>
    public string Language { get; set; } = string.Empty;

    /// <summary>
    /// Kullanicinin tercih ettigi gorunum temasi.
    /// </summary>
    public Theme Theme { get; set; }

    /// <summary>
    /// Kullanicinin tercih ettigi olcum birimi sistemi.
    /// </summary>
    public UnitSystem UnitSystem { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
