// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserStreak varligini temsil eder.
/// </summary>
public class UserStreak
{
    /// <summary>
    /// Seri (streak) kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Serinin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kullanicinin guncel ardisik gun sayisi.
    /// </summary>
    public int CurrentStreak { get; set; }

    /// <summary>
    /// Kullanicinin en uzun ardisik gun serisi.
    /// </summary>
    public int LongestStreak { get; set; }

    /// <summary>
    /// Son aktivite tarihi.
    /// </summary>
    public DateTime? LastActivityDate { get; set; }

    /// <summary>
    /// Kaydin son guncellenme tarihi.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
