// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserConsent varligini temsil eder.
/// </summary>
public class UserConsent
{
    /// <summary>
    /// Onay kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Onayi veren kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Onaylanan yasal belgenin kimligi.
    /// </summary>
    public Guid DocumentId { get; set; }

    /// <summary>
    /// Belgenin kabul edilip edilmedigi.
    /// </summary>
    public bool Accepted { get; set; }

    /// <summary>
    /// Belgenin kabul edildigi tarih.
    /// </summary>
    public DateTime AcceptedAt { get; set; }

    /// <summary>
    /// Onayin verildigi IP adresi.
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// Onaylanan belge surumu.
    /// </summary>
    public string Version { get; set; } = string.Empty;
}
