// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// UserAchievement varligini temsil eder.
/// </summary>
public class UserAchievement
{
    /// <summary>
    /// Kullanici basarisi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Basariyi kazanan kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Kazanilan basarinin kimligi.
    /// </summary>
    public Guid AchievementId { get; set; }

    /// <summary>
    /// Basarinin kazanildigi tarih.
    /// </summary>
    public DateTime EarnedAt { get; set; }
}
