// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WaterLog varligini temsil eder.
/// </summary>
public class WaterLog
{
    /// <summary>
    /// Su tuketimi kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Kaydi olusturan kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Su tuketiminin gerceklestigi tarih.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Tuketilen su miktari (mililitre).
    /// </summary>
    public decimal AmountMl { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
