// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutSession varligini temsil eder.
/// </summary>
public class WorkoutSession
{
    /// <summary>
    /// Antrenman oturumunun benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Oturumu gerceklestiren kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Gerceklestirilen antrenmanin kimligi.
    /// </summary>
    public Guid WorkoutId { get; set; }

    /// <summary>
    /// Oturumun baslangic tarihi/saati.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Oturumun tamamlanma tarihi/saati.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Oturumun guncel durumu.
    /// </summary>
    public WorkoutSessionStatus Status { get; set; }

    /// <summary>
    /// Oturumun toplam suresi (saniye).
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// Oturumda yakilan tahmini kalori.
    /// </summary>
    public decimal? CaloriesBurned { get; set; }

    /// <summary>
    /// Oturuma ait notlar.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
