// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutPlanDay varligini temsil eder.
/// </summary>
public class WorkoutPlanDay
{
    /// <summary>
    /// Plan gunu kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili antrenman planinin kimligi.
    /// </summary>
    public Guid WorkoutPlanId { get; set; }

    /// <summary>
    /// Antrenmanin planlandigi haftanin gunu.
    /// </summary>
    public DayOfWeek DayOfWeek { get; set; }

    /// <summary>
    /// O gun icin planlanan antrenmanin kimligi.
    /// </summary>
    public Guid WorkoutId { get; set; }

    /// <summary>
    /// Ayni gun icindeki siralama degeri.
    /// </summary>
    public int Order { get; set; }
}
