// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutSetLog varligini temsil eder.
/// </summary>
public class WorkoutSetLog
{
    /// <summary>
    /// Set kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili oturum-egzersiz kaydinin kimligi.
    /// </summary>
    public Guid WorkoutSessionExerciseId { get; set; }

    /// <summary>
    /// Setin sira numarasi.
    /// </summary>
    public int SetNumber { get; set; }

    /// <summary>
    /// Sette kullanilan agirlik (kilogram).
    /// </summary>
    public decimal? WeightKg { get; set; }

    /// <summary>
    /// Sette yapilan tekrar sayisi.
    /// </summary>
    public int? Reps { get; set; }

    /// <summary>
    /// Sureye dayali setler icin sure (saniye).
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// Setin tamamlanma tarihi/saati.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Setin algilanan zorluk derecesi (RPE).
    /// </summary>
    public decimal? Rpe { get; set; }

    /// <summary>
    /// Sete ait notlar.
    /// </summary>
    public string? Notes { get; set; }
}
