// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutPlan varligini temsil eder.
/// </summary>
public class WorkoutPlan
{
    /// <summary>
    /// Antrenman planinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Planin ait oldugu kullanicinin kimligi.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Planin adi.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Planin aciklamasi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Planin hedefledigi fitness hedefi.
    /// </summary>
    public FitnessGoal? Goal { get; set; }

    /// <summary>
    /// Planin baslangic tarihi.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Planin bitis tarihi.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Planin aktif olup olmadigi.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Planin yapay zeka tarafindan uretilip uretilmedigi.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Kaydin olusturulma tarihi.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
