// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutSessionExercise varligini temsil eder.
/// </summary>
public class WorkoutSessionExercise
{
    /// <summary>
    /// Oturum-egzersiz kaydinin benzersiz kimligi.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Iliskili antrenman oturumunun kimligi.
    /// </summary>
    public Guid WorkoutSessionId { get; set; }

    /// <summary>
    /// Gerceklestirilen egzersizin kimligi.
    /// </summary>
    public Guid ExerciseId { get; set; }

    /// <summary>
    /// Egzersizin oturum icindeki sirasi.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// Egzersizin baslangic tarihi/saati.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Egzersizin tamamlanma tarihi/saati.
    /// </summary>
    public DateTime? CompletedAt { get; set; }
}
