// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutPlanDay varligini temsil eder.
/// </summary>
public class WorkoutPlanDay : BaseEntity
{
    /// <summary>
    /// Iliskili antrenman planinin kimligi.
    /// </summary>
    public long WorkoutPlanId { get; set; }

    /// <summary>
    /// Antrenmanin planlandigi haftanin gunu.
    /// </summary>
    public DayOfWeek DayOfWeek { get; set; }

    /// <summary>
    /// O gun icin planlanan antrenmanin kimligi.
    /// </summary>
    public long WorkoutId { get; set; }

    /// <summary>
    /// Ayni gun icindeki siralama degeri.
    /// </summary>
    public int Order { get; set; }
}
