// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutEquipment varligini temsil eder.
/// </summary>
public class WorkoutEquipment
{
    /// <summary>
    /// Iliskili antrenmanin kimligi.
    /// </summary>
    public Guid WorkoutId { get; set; }

    /// <summary>
    /// Iliskili ekipmanin kimligi.
    /// </summary>
    public Guid EquipmentId { get; set; }
}
