// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutEquipment varligini temsil eder.
/// </summary>
public class WorkoutEquipment : BaseEntity
{
    /// <summary>
    /// Iliskili antrenmanin kimligi.
    /// </summary>
    public long WorkoutId { get; set; }

    /// <summary>
    /// Iliskili ekipmanin kimligi.
    /// </summary>
    public long EquipmentId { get; set; }
}
