// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using MerfitApi.Domain.Common;

namespace MerfitApi.Domain.Entities;

/// <summary>
/// WorkoutSessionExercise varligini temsil eder.
/// </summary>
public class WorkoutSessionExercise : BaseEntity
{
    /// <summary>
    /// Iliskili antrenman oturumunun kimligi.
    /// </summary>
    public long WorkoutSessionId { get; set; }

    /// <summary>
    /// Gerceklestirilen egzersizin kimligi.
    /// </summary>
    public long ExerciseId { get; set; }

    /// <summary>
    /// Egzersizin oturum icindeki sirasi.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// Egzersizin baslangic tarihi/saati.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Egzersizin tamamlanma tarihi/saati.
    /// </summary>
    public DateTime? CompletedAt { get; set; }
}
