// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

namespace MerfitApi.Domain.Entities.Enums;

/// <summary>
/// Ogunun turunu ifade eder.
/// </summary>
public enum MealType
{
    /// <summary>
    /// Kahvalti.
    /// </summary>
    Breakfast,
    /// <summary>
    /// Ogle yemegi.
    /// </summary>
    Lunch,
    /// <summary>
    /// Aksam yemegi.
    /// </summary>
    Dinner,
    /// <summary>
    /// Ara ogun.
    /// </summary>
    Snack
}
