// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// ApplicationUser varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class ApplicationUserConfiguration : IEntityTypeConfiguration<ApplicationUser>
{
    /// <summary>
    /// ApplicationUser varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<ApplicationUser> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Users");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kullanicinin e-posta adresi.
        builder.Property(x => x.Email)
            .IsRequired(true)
            .HasMaxLength(500);

        // Karsilastirma icin normallestirilmis (buyuk harfe cevrilmis) e-posta adresi.
        builder.Property(x => x.NormalizedEmail)
            .IsRequired(true)
            .HasMaxLength(500);

        // Kullanicinin kullanici adi.
        builder.Property(x => x.UserName)
            .IsRequired(true)
            .HasMaxLength(500);

        // Karsilastirma icin normallestirilmis kullanici adi.
        builder.Property(x => x.NormalizedUserName)
            .IsRequired(true)
            .HasMaxLength(500);

        // Kullanicinin sifrelenmis (hash'lenmis) parolasi.
        builder.Property(x => x.PasswordHash)
            .IsRequired(true)
            .HasMaxLength(500);

        // Kullanicinin telefon numarasi.
        builder.Property(x => x.PhoneNumber)
            .IsRequired(false)
            .HasMaxLength(300);

        // Kullanicinin yetki seviyesi (User/Admin/SuperAdmin); okunabilirlik icin string olarak saklanir.
        builder.Property(x => x.Role)
            .IsRequired(true)
            .HasMaxLength(50)
            .HasConversion<string>()
            .HasDefaultValue(MerfitApi.Domain.Entities.Enums.UserRole.User);

        // Admin panelinde role gore filtreleme/istatistik sorgulari icin indeks.
        builder.HasIndex(x => x.Role);

        // Soft-delete + aktiflik durumuna gore filtrelenen admin kullanici listeleri icin indeks.
        builder.HasIndex(x => new { x.IsActive, x.DeletedAt });
    }
}
