// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// Equipment varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class EquipmentConfiguration : IEntityTypeConfiguration<Equipment>
{
    /// <summary>
    /// Equipment varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Equipment> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Equipments");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Ekipmanin adi (orn. Dambil, Halter).
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Ekipmanin URL dostu kisa adi.
        builder.Property(x => x.Slug)
            .IsRequired(true)
            .HasMaxLength(200);
    }
}
