// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// Feature varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class FeatureConfiguration : IEntityTypeConfiguration<Feature>
{
    /// <summary>
    /// Feature varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<Feature> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("Features");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Ozelligin sistemsel kodu (orn. AI_WORKOUT).
        builder.Property(x => x.Code)
            .IsRequired(true)
            .HasMaxLength(200);

        // Ozelligin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Ozelligin aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);
    }
}
