// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;
using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// LegalDocument varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class LegalDocumentConfiguration : IEntityTypeConfiguration<LegalDocument>
{
    /// <summary>
    /// LegalDocument varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<LegalDocument> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("LegalDocuments", "content");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Belgenin turu.
        builder.Property(x => x.Type)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Belgenin surum numarasi.
        builder.Property(x => x.Version)
            .IsRequired(true)
            .HasMaxLength(300);

        // Belgenin diline ait kod.
        builder.Property(x => x.Language)
            .IsRequired(true)
            .HasMaxLength(200);

        // Belgenin basligi.
        builder.Property(x => x.Title)
            .IsRequired(true)
            .HasMaxLength(200);

        // Belgenin icerik metni.
        builder.Property(x => x.Content)
            .IsRequired(true)
            .HasMaxLength(2000);
    }
}
