// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// MerfitScoreHistory varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class MerfitScoreHistoryConfiguration : IEntityTypeConfiguration<MerfitScoreHistory>
{
    /// <summary>
    /// MerfitScoreHistory varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<MerfitScoreHistory> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("MerfitScoreHistories");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Kaydedilen skor degeri.
        builder.Property(x => x.Score)
            .HasPrecision(18, 2);

        // Iliskiler (foreign key) yapilandirmasi.
        // Skorun ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
