// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;
using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// SupportTicket varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class SupportTicketConfiguration : IEntityTypeConfiguration<SupportTicket>
{
    /// <summary>
    /// SupportTicket varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<SupportTicket> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("SupportTicket", "support");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Talebin konusu.
        builder.Property(x => x.Subject)
            .IsRequired(true)
            .HasMaxLength(300);

        // Talebin ilk mesaj icerigi.
        builder.Property(x => x.Message)
            .IsRequired(true)
            .HasMaxLength(2000);

        // Talebin guncel durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Talebin oncelik seviyesi.
        builder.Property(x => x.Priority)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Talebi olusturan kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
