// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// UserPrivacySetting varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserPrivacySettingConfiguration : IEntityTypeConfiguration<UserPrivacySetting>
{
    /// <summary>
    /// UserPrivacySetting varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserPrivacySetting> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserPrivacySettings");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Iliskiler (foreign key) yapilandirmasi.
        // Ayarin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
