// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;
using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// UserReward varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class UserRewardConfiguration : IEntityTypeConfiguration<UserReward>
{
    /// <summary>
    /// UserReward varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<UserReward> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("UserRewards");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Odulun guncel durumu.
        builder.Property(x => x.Status)
            .HasConversion<string>()
            .IsRequired(true)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Odulu kazanan kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Kazanilan odulun kimligi.
        builder.HasOne<Reward>()
            .WithMany()
            .HasForeignKey(x => x.RewardId)
            .OnDelete(DeleteBehavior.Restrict);

        // Odulun kazanildigi liderlik donemi kimligi.
        builder.HasOne<LeaderboardPeriod>()
            .WithMany()
            .HasForeignKey(x => x.LeaderboardPeriodId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
