// <auto-generated>
// Bu dosya Claude tarafindan MerfitApi.Domain.Entities namespace'i icin olusturulmustur.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MerfitApi.Domain.Entities;
using MerfitApi.Domain.Entities.Enums;

namespace MerfitApi.Infrastructure.Configurations;

/// <summary>
/// WorkoutPlan varliginin veritabani (Entity Framework Core) yapilandirmasini tanimlar.
/// </summary>
public class WorkoutPlanConfiguration : IEntityTypeConfiguration<WorkoutPlan>
{
    /// <summary>
    /// WorkoutPlan varligi icin tablo adi, birincil anahtar, alan kisitlari ve iliskileri yapilandirir.
    /// </summary>
    public void Configure(EntityTypeBuilder<WorkoutPlan> builder)
    {
        // Tablo adini belirtir.
        builder.ToTable("WorkoutPlans");

        // Birincil anahtari tanimlar.
        builder.HasKey(x => x.Id);

        // Planin adi.
        builder.Property(x => x.Name)
            .IsRequired(true)
            .HasMaxLength(200);

        // Planin aciklamasi.
        builder.Property(x => x.Description)
            .IsRequired(false)
            .HasMaxLength(2000);

        // Planin hedefledigi fitness hedefi.
        builder.Property(x => x.Goal)
            .HasConversion<string>()
            .IsRequired(false)
            .HasMaxLength(50);

        // Iliskiler (foreign key) yapilandirmasi.
        // Planin ait oldugu kullanicinin kimligi.
        builder.HasOne<ApplicationUser>()
            .WithMany()
            .HasForeignKey(x => x.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
