-- =============================================================================
-- MerfitApi - PostgreSQL semasi ve tablo olusturma script'i
-- =============================================================================
-- Bu script; MerfitApi.Domain/Entities altindaki entity siniflari ve
-- MerfitApi.Infrastructure/Configurations altindaki EF Core (Npgsql) yapilandirmalari
-- referans alinarak elle yazilmistir. Yalnizca semayi ve tablolari olusturur;
-- rol/kullanici, extension, seed veri gibi baska hicbir islem yapmaz.
--
-- On kosul: veritabani zaten olusturulmus olmali, orn:
--   CREATE DATABASE merfit OWNER merfit_app;
--
-- Kullanim (Ubuntu 24.04, psql):
--   psql -h localhost -U merfit_app -d merfit -f 001_create_schema_and_tables.sql
--
-- Notlar:
--   * Tum tablo/kolon adlari EF Core (Npgsql) varsayilan davranisina uyacak sekilde
--     entity/property adlariyla BIREBIR (PascalCase, tirnakli) tutulmustur. Ileride
--     `dotnet ef migrations` kullanilacaksa isimler boylece EF modeliyle eslesir.
--   * decimal alanlar EF yapilandirmasindaki HasPrecision(18,2) degerine gore
--     NUMERIC(18,2) olarak tanimlanmistir.
--   * enum alanlar EF yapilandirmasinda HasConversion<string>().HasMaxLength(50)
--     ile string olarak saklandigi icin VARCHAR(50) + CHECK constraint olarak
--     modellenmistir. Tek istisna WorkoutPlanDay.DayOfWeek (.NET System.DayOfWeek);
--     bu alan icin EF tarafinda ozel bir konfigurasyon olmadigindan varsayilan
--     davranisla INTEGER (0=Sunday .. 6=Saturday) olarak saklanir.
--   * WorkoutEquipments ve SubscriptionPlanFeatures tablolarinda BaseEntity'den
--     gelen "Id" kolonu, EF konfigurasyonunda birlesik (composite) anahtar
--     kullanildigi icin PRIMARY KEY DEGILDIR ve otomatik artan (identity) da
--     degildir; sadece model ile birebir eslesmesi icin NOT NULL bir kolon
--     olarak tutulmustur.
-- =============================================================================

-- Bu script'in yarattigi sema ve tablolarin sahibi merfit_app olsun diye,
-- superuser (orn. postgres) ile baglanildiysa role gecisi yapilir. merfit_app
-- ile dogrudan baglanildiysa bu satir zararsizdir (bir rol kendine gecebilir).
SET ROLE merfit_app;

-- -----------------------------------------------------------------------------
-- 1) SEMA
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS merfit AUTHORIZATION merfit_app;

SET search_path TO merfit;

-- -----------------------------------------------------------------------------
-- 2) TABLOLAR
-- -----------------------------------------------------------------------------

-- Achievement -----------------------------------------------------------------
CREATE TABLE "Achievements" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Code" VARCHAR(200) NOT NULL,
    "Title" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "Icon" VARCHAR(500) NULL,
    "Points" INTEGER NOT NULL,
    "ConditionType" VARCHAR(2000) NOT NULL,
    "ConditionValue" VARCHAR(2000) NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id")
);

-- AiGenerationRequest -----------------------------------------------------------
CREATE TABLE "AiGenerationRequests" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Type" VARCHAR(50) NOT NULL,
    "Prompt" VARCHAR(2000) NOT NULL,
    "Status" VARCHAR(50) NOT NULL,
    "Model" VARCHAR(2000) NULL,
    "StartedAt" TIMESTAMP NULL,
    "CompletedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_AiGenerationRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AiGenerationRequests_Type" CHECK ("Type" IN ('Workout','Nutrition','Insight')),
    CONSTRAINT "CK_AiGenerationRequests_Status" CHECK ("Status" IN ('Pending','Processing','Completed','Failed'))
);

-- AiGenerationResult --------------------------------------------------------
CREATE TABLE "AiGenerationResults" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "RequestId" BIGINT NOT NULL,
    "ResultJson" VARCHAR(2000) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_AiGenerationResults" PRIMARY KEY ("Id")
);

-- AppContent ------------------------------------------------------------------
CREATE TABLE "AppContents" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Key" VARCHAR(200) NOT NULL,
    "Type" VARCHAR(2000) NOT NULL,
    "Title" VARCHAR(200) NULL,
    "Description" VARCHAR(2000) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "LinkUrl" VARCHAR(500) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "StartAt" TIMESTAMP NULL,
    "EndAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_AppContents" PRIMARY KEY ("Id")
);

-- ApplicationUser (tablo adi: Users) -------------------------------------------
CREATE TABLE "Users" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Email" VARCHAR(500) NOT NULL,
    "NormalizedEmail" VARCHAR(500) NOT NULL,
    "UserName" VARCHAR(500) NOT NULL,
    "NormalizedUserName" VARCHAR(500) NOT NULL,
    "PasswordHash" VARCHAR(500) NOT NULL,
    "PhoneNumber" VARCHAR(300) NULL,
    "EmailConfirmed" BOOLEAN NOT NULL,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "LastLoginAt" TIMESTAMP NULL,
    "DeletedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- AuditLog ----------------------------------------------------------------------
CREATE TABLE "AuditLogs" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NULL,
    "Action" VARCHAR(2000) NOT NULL,
    "Entity" VARCHAR(2000) NOT NULL,
    "EntityId" BIGINT NULL,
    "IpAddress" VARCHAR(2000) NULL,
    "UserAgent" VARCHAR(2000) NULL,
    "MetadataJson" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

-- BodyMeasurement -----------------------------------------------------------
CREATE TABLE "BodyMeasurements" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "RecordedAt" TIMESTAMP NOT NULL,
    "WeightKg" NUMERIC(18,2) NULL,
    "BodyFatPercentage" NUMERIC(18,2) NULL,
    "BMI" NUMERIC(18,2) NULL,
    "ChestCm" NUMERIC(18,2) NULL,
    "WaistCm" NUMERIC(18,2) NULL,
    "HipCm" NUMERIC(18,2) NULL,
    "ArmCm" NUMERIC(18,2) NULL,
    "ThighCm" NUMERIC(18,2) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_BodyMeasurements" PRIMARY KEY ("Id")
);

-- Equipment ---------------------------------------------------------------------
CREATE TABLE "Equipments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "Slug" VARCHAR(200) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Equipments" PRIMARY KEY ("Id")
);

-- Exercise ------------------------------------------------------------------
CREATE TABLE "Exercises" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "Slug" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "Instructions" VARCHAR(2000) NULL,
    "Difficulty" VARCHAR(50) NOT NULL,
    "PrimaryMuscleGroupId" BIGINT NOT NULL,
    "EquipmentType" VARCHAR(2000) NULL,
    "VideoUrl" VARCHAR(500) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "CaloriesPerMinute" NUMERIC(18,2) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Exercises_Difficulty" CHECK ("Difficulty" IN ('Beginner','Intermediate','Advanced'))
);

-- ExternalLogin ---------------------------------------------------------------
CREATE TABLE "ExternalLogins" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Provider" VARCHAR(200) NOT NULL,
    "ProviderUserId" VARCHAR(200) NOT NULL,
    "Email" VARCHAR(500) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_ExternalLogins" PRIMARY KEY ("Id")
);

-- FAQCategory -------------------------------------------------------------------
CREATE TABLE "FAQCategories" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "SortOrder" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_FAQCategories" PRIMARY KEY ("Id")
);

-- FAQ -----------------------------------------------------------------------
CREATE TABLE "FAQs" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" BIGINT NOT NULL,
    "Question" VARCHAR(2000) NOT NULL,
    "Answer" VARCHAR(2000) NOT NULL,
    "SortOrder" INTEGER NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_FAQs" PRIMARY KEY ("Id")
);

-- Feature -----------------------------------------------------------------------
CREATE TABLE "Features" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Code" VARCHAR(200) NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Features" PRIMARY KEY ("Id")
);

-- Food ------------------------------------------------------------------------
CREATE TABLE "Foods" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "Barcode" VARCHAR(300) NULL,
    "Brand" VARCHAR(200) NULL,
    "ServingSize" NUMERIC(18,2) NOT NULL,
    "ServingUnit" VARCHAR(2000) NOT NULL,
    "Calories" NUMERIC(18,2) NOT NULL,
    "Protein" NUMERIC(18,2) NOT NULL,
    "Carbs" NUMERIC(18,2) NOT NULL,
    "Fat" NUMERIC(18,2) NOT NULL,
    "Fiber" NUMERIC(18,2) NULL,
    "Sugar" NUMERIC(18,2) NULL,
    "Sodium" NUMERIC(18,2) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Foods" PRIMARY KEY ("Id")
);

-- GoalHistory -----------------------------------------------------------------
CREATE TABLE "GoalHistories" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "OldGoal" VARCHAR(50) NOT NULL,
    "NewGoal" VARCHAR(50) NOT NULL,
    "ChangedAt" TIMESTAMP NOT NULL,
    "Reason" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_GoalHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_GoalHistories_OldGoal" CHECK ("OldGoal" IN ('LoseWeight','BuildMuscle','MaintainWeight','ImproveEndurance','GetStronger','ImproveFitness')),
    CONSTRAINT "CK_GoalHistories_NewGoal" CHECK ("NewGoal" IN ('LoseWeight','BuildMuscle','MaintainWeight','ImproveEndurance','GetStronger','ImproveFitness'))
);

-- Language ----------------------------------------------------------------------
CREATE TABLE "Languages" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Code" VARCHAR(200) NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "IsDefault" BOOLEAN NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);

-- LeaderboardPeriod -----------------------------------------------------------
CREATE TABLE "LeaderboardPeriods" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Type" VARCHAR(50) NOT NULL,
    "StartDate" TIMESTAMP NOT NULL,
    "EndDate" TIMESTAMP NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_LeaderboardPeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_LeaderboardPeriods_Type" CHECK ("Type" IN ('Weekly','Monthly','AllTime'))
);

-- LeaderboardEntry --------------------------------------------------------------
CREATE TABLE "LeaderboardEntries" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "LeaderboardPeriodId" BIGINT NOT NULL,
    "UserId" BIGINT NOT NULL,
    "Points" NUMERIC(18,2) NOT NULL,
    "WorkoutCount" INTEGER NOT NULL,
    "Rank" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_LeaderboardEntries" PRIMARY KEY ("Id")
);

-- Reward --------------------------------------------------------------------
CREATE TABLE "Rewards" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Title" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "RewardType" VARCHAR(2000) NOT NULL,
    "Value" VARCHAR(2000) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Rewards" PRIMARY KEY ("Id")
);

-- LeaderboardReward -------------------------------------------------------------
CREATE TABLE "LeaderboardRewards" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "LeaderboardPeriodId" BIGINT NOT NULL,
    "Rank" INTEGER NOT NULL,
    "RewardId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_LeaderboardRewards" PRIMARY KEY ("Id")
);

-- LegalDocument -----------------------------------------------------------------
CREATE TABLE "LegalDocuments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Type" VARCHAR(50) NOT NULL,
    "Version" VARCHAR(300) NOT NULL,
    "Language" VARCHAR(200) NOT NULL,
    "Title" VARCHAR(200) NOT NULL,
    "Content" VARCHAR(2000) NOT NULL,
    "PublishedAt" TIMESTAMP NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_LegalDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_LegalDocuments_Type" CHECK ("Type" IN ('PrivacyPolicy','TermsOfService'))
);

-- Meal ------------------------------------------------------------------------
CREATE TABLE "Meals" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Date" TIMESTAMP NOT NULL,
    "MealType" VARCHAR(50) NOT NULL,
    "Notes" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Meals" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Meals_MealType" CHECK ("MealType" IN ('Breakfast','Lunch','Dinner','Snack'))
);

-- Food alanina bagimli oldugu icin MealItems, Foods'tan sonra tanimlanir --------
CREATE TABLE "MealItems" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "MealId" BIGINT NOT NULL,
    "FoodId" BIGINT NOT NULL,
    "Quantity" NUMERIC(18,2) NOT NULL,
    "ServingSize" NUMERIC(18,2) NOT NULL,
    "Calories" NUMERIC(18,2) NOT NULL,
    "Protein" NUMERIC(18,2) NOT NULL,
    "Carbs" NUMERIC(18,2) NOT NULL,
    "Fat" NUMERIC(18,2) NOT NULL,
    "Fiber" NUMERIC(18,2) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_MealItems" PRIMARY KEY ("Id")
);

-- MerfitScore -------------------------------------------------------------------
CREATE TABLE "MerfitScores" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Score" NUMERIC(18,2) NOT NULL,
    "Period" VARCHAR(300) NOT NULL,
    "CalculatedAt" TIMESTAMP NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_MerfitScores" PRIMARY KEY ("Id")
);

-- MerfitScoreBreakdown ------------------------------------------------------
CREATE TABLE "MerfitScoreBreakdowns" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "MerfitScoreId" BIGINT NOT NULL,
    "Category" VARCHAR(300) NOT NULL,
    "Points" NUMERIC(18,2) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_MerfitScoreBreakdowns" PRIMARY KEY ("Id")
);

-- MerfitScoreHistory ----------------------------------------------------------
CREATE TABLE "MerfitScoreHistories" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Score" NUMERIC(18,2) NOT NULL,
    "RecordedAt" TIMESTAMP NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_MerfitScoreHistories" PRIMARY KEY ("Id")
);

-- MuscleGroup -------------------------------------------------------------------
CREATE TABLE "MuscleGroups" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "Slug" VARCHAR(200) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_MuscleGroups" PRIMARY KEY ("Id")
);

-- Notification ------------------------------------------------------------------
CREATE TABLE "Notifications" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Type" VARCHAR(50) NOT NULL,
    "Title" VARCHAR(200) NOT NULL,
    "Body" VARCHAR(300) NOT NULL,
    "DataJson" VARCHAR(2000) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "IsRead" BOOLEAN NOT NULL,
    "ReadAt" TIMESTAMP NULL,
    "ExpiresAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Notifications_Type" CHECK ("Type" IN ('WorkoutReminder','GoalReminder','StreakReminder','ProgressUpdate','LeaderboardUpdate','Achievement','Reward','Subscription','System','Marketing'))
);

-- NutritionGoal -----------------------------------------------------------------
CREATE TABLE "NutritionGoals" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "DailyCalories" NUMERIC(18,2) NOT NULL,
    "ProteinTarget" NUMERIC(18,2) NOT NULL,
    "CarbsTarget" NUMERIC(18,2) NOT NULL,
    "FatTarget" NUMERIC(18,2) NOT NULL,
    "WaterTargetMl" NUMERIC(18,2) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_NutritionGoals" PRIMARY KEY ("Id")
);

-- WorkoutCategory, MuscleGroup ve Workout on kosullari -------------------------
CREATE TABLE "WorkoutCategories" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Name" VARCHAR(200) NOT NULL,
    "Slug" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "Workouts" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Title" VARCHAR(200) NOT NULL,
    "Slug" VARCHAR(200) NOT NULL,
    "Tagline" VARCHAR(300) NULL,
    "Description" VARCHAR(2000) NULL,
    "DurationMin" INTEGER NOT NULL,
    "Difficulty" VARCHAR(50) NOT NULL,
    "CategoryId" BIGINT NOT NULL,
    "MuscleGroupId" BIGINT NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "IsFeatured" BOOLEAN NOT NULL,
    "IsPremium" BOOLEAN NOT NULL,
    "IsAiGenerated" BOOLEAN NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Workouts" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Workouts_Difficulty" CHECK ("Difficulty" IN ('Beginner','Intermediate','Advanced'))
);

-- PersonalRecord'un bagli oldugu WorkoutSessions tanimindan once Workouts gerekir
CREATE TABLE "WorkoutSessions" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "WorkoutId" BIGINT NOT NULL,
    "StartedAt" TIMESTAMP NOT NULL,
    "CompletedAt" TIMESTAMP NULL,
    "Status" VARCHAR(50) NOT NULL,
    "DurationSeconds" INTEGER NULL,
    "CaloriesBurned" NUMERIC(18,2) NULL,
    "Notes" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_WorkoutSessions_Status" CHECK ("Status" IN ('Started','Paused','Completed','Cancelled','Abandoned'))
);

-- PersonalRecord ------------------------------------------------------------
CREATE TABLE "PersonalRecords" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "ExerciseId" BIGINT NOT NULL,
    "WeightKg" NUMERIC(18,2) NOT NULL,
    "Reps" INTEGER NOT NULL,
    "EstimatedOneRepMax" NUMERIC(18,2) NOT NULL,
    "AchievedAt" TIMESTAMP NOT NULL,
    "WorkoutSessionId" BIGINT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_PersonalRecords" PRIMARY KEY ("Id")
);

-- Subscription ------------------------------------------------------------------
CREATE TABLE "SubscriptionProducts" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Code" VARCHAR(200) NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "StoreProductIdIos" VARCHAR(300) NULL,
    "StoreProductIdAndroid" VARCHAR(300) NULL,
    "BillingPeriod" VARCHAR(50) NOT NULL,
    "Price" NUMERIC(18,2) NOT NULL,
    "Currency" VARCHAR(200) NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_SubscriptionProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SubscriptionProducts_BillingPeriod" CHECK ("BillingPeriod" IN ('Monthly','Yearly'))
);

CREATE TABLE "Subscriptions" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "SubscriptionProductId" BIGINT NOT NULL,
    "Provider" VARCHAR(50) NOT NULL,
    "ExternalTransactionId" VARCHAR(300) NULL,
    "Status" VARCHAR(50) NOT NULL,
    "StartedAt" TIMESTAMP NOT NULL,
    "ExpiresAt" TIMESTAMP NULL,
    "AutoRenew" BOOLEAN NOT NULL,
    "CancelledAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Subscriptions_Provider" CHECK ("Provider" IN ('Apple','Google')),
    CONSTRAINT "CK_Subscriptions_Status" CHECK ("Status" IN ('Active','Expired','Cancelled','Refunded','Paused','GracePeriod'))
);

CREATE TABLE "SubscriptionTransactions" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "SubscriptionId" BIGINT NOT NULL,
    "Provider" VARCHAR(50) NOT NULL,
    "TransactionId" VARCHAR(300) NOT NULL,
    "OriginalTransactionId" VARCHAR(300) NULL,
    "ProductId" VARCHAR(200) NOT NULL,
    "Amount" NUMERIC(18,2) NOT NULL,
    "Currency" VARCHAR(200) NOT NULL,
    "PurchasedAt" TIMESTAMP NOT NULL,
    "ExpiresAt" TIMESTAMP NULL,
    "RawReceipt" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_SubscriptionTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SubscriptionTransactions_Provider" CHECK ("Provider" IN ('Apple','Google'))
);

-- SubscriptionPlanFeature (birlesik anahtar) -------------------------------
CREATE TABLE "SubscriptionPlanFeatures" (
    "Id" BIGINT NOT NULL,
    "SubscriptionProductId" BIGINT NOT NULL,
    "FeatureId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_SubscriptionPlanFeatures" PRIMARY KEY ("SubscriptionProductId", "FeatureId")
);

-- SupportTicket -----------------------------------------------------------------
CREATE TABLE "SupportTickets" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Subject" VARCHAR(300) NOT NULL,
    "Message" VARCHAR(2000) NOT NULL,
    "Status" VARCHAR(50) NOT NULL,
    "Priority" VARCHAR(50) NOT NULL,
    "ClosedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_SupportTickets_Status" CHECK ("Status" IN ('Open','InProgress','Resolved','Closed')),
    CONSTRAINT "CK_SupportTickets_Priority" CHECK ("Priority" IN ('Low','Medium','High','Urgent'))
);

CREATE TABLE "SupportTicketMessages" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "TicketId" BIGINT NOT NULL,
    "SenderUserId" BIGINT NOT NULL,
    "Message" VARCHAR(2000) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_SupportTicketMessages" PRIMARY KEY ("Id")
);

-- Translation -------------------------------------------------------------------
CREATE TABLE "Translations" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "LanguageId" BIGINT NOT NULL,
    "ResourceKey" VARCHAR(200) NOT NULL,
    "Value" VARCHAR(2000) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_Translations" PRIMARY KEY ("Id")
);

-- UserAchievement -----------------------------------------------------------
CREATE TABLE "UserAchievements" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "AchievementId" BIGINT NOT NULL,
    "EarnedAt" TIMESTAMP NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserAchievements" PRIMARY KEY ("Id")
);

-- UserConsent -------------------------------------------------------------------
CREATE TABLE "UserConsents" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "DocumentId" BIGINT NOT NULL,
    "Accepted" BOOLEAN NOT NULL,
    "AcceptedAt" TIMESTAMP NOT NULL,
    "IpAddress" VARCHAR(2000) NULL,
    "Version" VARCHAR(300) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserConsents" PRIMARY KEY ("Id")
);

-- UserDevice ----------------------------------------------------------------
CREATE TABLE "UserDevices" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "DeviceToken" VARCHAR(500) NOT NULL,
    "Platform" VARCHAR(50) NOT NULL,
    "DeviceName" VARCHAR(200) NULL,
    "AppVersion" VARCHAR(300) NULL,
    "OsVersion" VARCHAR(300) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "LastSeenAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserDevices" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserDevices_Platform" CHECK ("Platform" IN ('IOS','Android','Web'))
);

-- UserEquipment -----------------------------------------------------------------
CREATE TABLE "UserEquipments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "EquipmentId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserEquipments" PRIMARY KEY ("Id")
);

-- UserGoal ------------------------------------------------------------------
CREATE TABLE "UserGoals" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "GoalType" VARCHAR(50) NOT NULL,
    "StartingWeightKg" NUMERIC(18,2) NULL,
    "CurrentWeightKg" NUMERIC(18,2) NULL,
    "TargetWeightKg" NUMERIC(18,2) NULL,
    "TargetDate" TIMESTAMP NULL,
    "ProgressPercent" NUMERIC(18,2) NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CompletedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserGoals" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserGoals_GoalType" CHECK ("GoalType" IN ('LoseWeight','BuildMuscle','MaintainWeight','ImproveEndurance','GetStronger','ImproveFitness'))
);

-- UserNotificationSetting --------------------------------------------------------
CREATE TABLE "UserNotificationSettings" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "WorkoutReminders" BOOLEAN NOT NULL,
    "DailyGoalReminder" BOOLEAN NOT NULL,
    "StreakReminder" BOOLEAN NOT NULL,
    "ProgressUpdates" BOOLEAN NOT NULL,
    "LeaderboardUpdates" BOOLEAN NOT NULL,
    "ProductUpdates" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserNotificationSettings" PRIMARY KEY ("Id")
);

-- UserPreference ----------------------------------------------------------------
CREATE TABLE "UserPreferences" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Language" VARCHAR(200) NOT NULL,
    "Theme" VARCHAR(50) NOT NULL,
    "UnitSystem" VARCHAR(50) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserPreferences_Theme" CHECK ("Theme" IN ('Light','Dark','System')),
    CONSTRAINT "CK_UserPreferences_UnitSystem" CHECK ("UnitSystem" IN ('Metric','Imperial'))
);

-- UserPrivacySetting -----------------------------------------------------------
CREATE TABLE "UserPrivacySettings" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "ProfileVisibleOnLeaderboard" BOOLEAN NOT NULL,
    "ShareWorkoutStatistics" BOOLEAN NOT NULL,
    "PersonalizedRecommendations" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserPrivacySettings" PRIMARY KEY ("Id")
);

-- UserProfile -------------------------------------------------------------------
CREATE TABLE "UserProfiles" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "FirstName" VARCHAR(200) NOT NULL,
    "LastName" VARCHAR(200) NOT NULL,
    "Username" VARCHAR(300) NOT NULL,
    "DateOfBirth" TIMESTAMP NULL,
    "Gender" VARCHAR(50) NULL,
    "HeightCm" NUMERIC(18,2) NULL,
    "WeightKg" NUMERIC(18,2) NULL,
    "TargetWeightKg" NUMERIC(18,2) NULL,
    "ProfileImageUrl" VARCHAR(500) NULL,
    "Goal" VARCHAR(50) NULL,
    "ExperienceLevel" VARCHAR(50) NULL,
    "WorkoutDurationMin" INTEGER NULL,
    "ActivityLevel" VARCHAR(50) NULL,
    "TrainingLocation" VARCHAR(50) NULL,
    "TrainingDaysPerWeek" INTEGER NULL,
    "UnitSystem" VARCHAR(50) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserProfiles_Gender" CHECK ("Gender" IN ('Male','Female','Other')),
    CONSTRAINT "CK_UserProfiles_Goal" CHECK ("Goal" IN ('LoseWeight','BuildMuscle','MaintainWeight','ImproveEndurance','GetStronger','ImproveFitness')),
    CONSTRAINT "CK_UserProfiles_ExperienceLevel" CHECK ("ExperienceLevel" IN ('Beginner','Intermediate','Advanced')),
    CONSTRAINT "CK_UserProfiles_ActivityLevel" CHECK ("ActivityLevel" IN ('Sedentary','LightlyActive','ModeratelyActive','VeryActive','ExtraActive')),
    CONSTRAINT "CK_UserProfiles_TrainingLocation" CHECK ("TrainingLocation" IN ('Home','Gym','Outdoor')),
    CONSTRAINT "CK_UserProfiles_UnitSystem" CHECK ("UnitSystem" IN ('Metric','Imperial'))
);

-- UserRefreshToken --------------------------------------------------------------
CREATE TABLE "UserRefreshTokens" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Token" VARCHAR(500) NOT NULL,
    "ExpiresAt" TIMESTAMP NOT NULL,
    "RevokedAt" TIMESTAMP NULL,
    "CreatedByIp" VARCHAR(300) NULL,
    "RevokedByIp" VARCHAR(300) NULL,
    "ReplacementToken" VARCHAR(500) NULL,
    "IsRevoked" BOOLEAN NOT NULL,
    "IsUsed" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("Id")
);

-- UserReward ------------------------------------------------------------------
CREATE TABLE "UserRewards" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "RewardId" BIGINT NOT NULL,
    "LeaderboardPeriodId" BIGINT NULL,
    "Rank" INTEGER NULL,
    "Status" VARCHAR(50) NOT NULL,
    "ClaimedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserRewards" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserRewards_Status" CHECK ("Status" IN ('Pending','Claimed','Expired','Cancelled'))
);

-- UserStreak --------------------------------------------------------------------
CREATE TABLE "UserStreaks" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "CurrentStreak" INTEGER NOT NULL,
    "LongestStreak" INTEGER NOT NULL,
    "LastActivityDate" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_UserStreaks" PRIMARY KEY ("Id")
);

-- WaterLog ------------------------------------------------------------------
CREATE TABLE "WaterLogs" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Date" TIMESTAMP NOT NULL,
    "AmountMl" NUMERIC(18,2) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WaterLogs" PRIMARY KEY ("Id")
);

-- WorkoutEquipment (birlesik anahtar) --------------------------------------
CREATE TABLE "WorkoutEquipments" (
    "Id" BIGINT NOT NULL,
    "WorkoutId" BIGINT NOT NULL,
    "EquipmentId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutEquipments" PRIMARY KEY ("WorkoutId", "EquipmentId")
);

-- WorkoutExercise ---------------------------------------------------------------
CREATE TABLE "WorkoutExercises" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutId" BIGINT NOT NULL,
    "ExerciseId" BIGINT NOT NULL,
    "Order" INTEGER NOT NULL,
    "Sets" INTEGER NOT NULL,
    "Reps" INTEGER NULL,
    "RestSeconds" INTEGER NULL,
    "DurationSeconds" INTEGER NULL,
    "Notes" VARCHAR(2000) NULL,
    "IsOptional" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutExercises" PRIMARY KEY ("Id")
);

-- WorkoutPlan -------------------------------------------------------------------
CREATE TABLE "WorkoutPlans" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId" BIGINT NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "Goal" VARCHAR(50) NULL,
    "StartDate" TIMESTAMP NOT NULL,
    "EndDate" TIMESTAMP NULL,
    "IsActive" BOOLEAN NOT NULL,
    "IsAiGenerated" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutPlans" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_WorkoutPlans_Goal" CHECK ("Goal" IN ('LoseWeight','BuildMuscle','MaintainWeight','ImproveEndurance','GetStronger','ImproveFitness'))
);

-- WorkoutPlanDay ----------------------------------------------------------------
-- NOT: "DayOfWeek" .NET'in yerlesik System.DayOfWeek enum'udur (Sunday=0..Saturday=6)
-- ve EF yapilandirmasinda ozel bir donusum tanimlanmamistir; bu yuzden INTEGER olarak saklanir.
CREATE TABLE "WorkoutPlanDays" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutPlanId" BIGINT NOT NULL,
    "DayOfWeek" INTEGER NOT NULL,
    "WorkoutId" BIGINT NOT NULL,
    "Order" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutPlanDays" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_WorkoutPlanDays_DayOfWeek" CHECK ("DayOfWeek" BETWEEN 0 AND 6)
);

-- WorkoutSessionExercise ----------------------------------------------------
CREATE TABLE "WorkoutSessionExercises" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutSessionId" BIGINT NOT NULL,
    "ExerciseId" BIGINT NOT NULL,
    "Order" INTEGER NOT NULL,
    "StartedAt" TIMESTAMP NULL,
    "CompletedAt" TIMESTAMP NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutSessionExercises" PRIMARY KEY ("Id")
);

-- WorkoutSetLog -----------------------------------------------------------------
CREATE TABLE "WorkoutSetLogs" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "WorkoutSessionExerciseId" BIGINT NOT NULL,
    "SetNumber" INTEGER NOT NULL,
    "WeightKg" NUMERIC(18,2) NULL,
    "Reps" INTEGER NULL,
    "DurationSeconds" INTEGER NULL,
    "CompletedAt" TIMESTAMP NULL,
    "Rpe" NUMERIC(18,2) NULL,
    "Notes" VARCHAR(2000) NULL,
    "CreatedAt" TIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP NULL,
    "CreatedUser" BIGINT NULL,
    "UpdatedUser" BIGINT NULL,
    CONSTRAINT "PK_WorkoutSetLogs" PRIMARY KEY ("Id")
);

-- -----------------------------------------------------------------------------
-- 3) FOREIGN KEY KISITLARI
--    (EF Core Configurations altindaki HasOne/.../OnDelete degerleriyle birebir)
-- -----------------------------------------------------------------------------

ALTER TABLE "AiGenerationRequests"
    ADD CONSTRAINT "FK_AiGenerationRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AiGenerationResults"
    ADD CONSTRAINT "FK_AiGenerationResults_AiGenerationRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "AiGenerationRequests" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AuditLogs"
    ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;

ALTER TABLE "BodyMeasurements"
    ADD CONSTRAINT "FK_BodyMeasurements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Exercises"
    ADD CONSTRAINT "FK_Exercises_MuscleGroups_PrimaryMuscleGroupId" FOREIGN KEY ("PrimaryMuscleGroupId") REFERENCES "MuscleGroups" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ExternalLogins"
    ADD CONSTRAINT "FK_ExternalLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "FAQs"
    ADD CONSTRAINT "FK_FAQs_FAQCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "FAQCategories" ("Id") ON DELETE RESTRICT;

ALTER TABLE "GoalHistories"
    ADD CONSTRAINT "FK_GoalHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "LeaderboardEntries"
    ADD CONSTRAINT "FK_LeaderboardEntries_LeaderboardPeriods_LeaderboardPeriodId" FOREIGN KEY ("LeaderboardPeriodId") REFERENCES "LeaderboardPeriods" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_LeaderboardEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "LeaderboardRewards"
    ADD CONSTRAINT "FK_LeaderboardRewards_LeaderboardPeriods_LeaderboardPeriodId" FOREIGN KEY ("LeaderboardPeriodId") REFERENCES "LeaderboardPeriods" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_LeaderboardRewards_Rewards_RewardId" FOREIGN KEY ("RewardId") REFERENCES "Rewards" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Meals"
    ADD CONSTRAINT "FK_Meals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "MealItems"
    ADD CONSTRAINT "FK_MealItems_Meals_MealId" FOREIGN KEY ("MealId") REFERENCES "Meals" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_MealItems_Foods_FoodId" FOREIGN KEY ("FoodId") REFERENCES "Foods" ("Id") ON DELETE RESTRICT;

ALTER TABLE "MerfitScores"
    ADD CONSTRAINT "FK_MerfitScores_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "MerfitScoreBreakdowns"
    ADD CONSTRAINT "FK_MerfitScoreBreakdowns_MerfitScores_MerfitScoreId" FOREIGN KEY ("MerfitScoreId") REFERENCES "MerfitScores" ("Id") ON DELETE RESTRICT;

ALTER TABLE "MerfitScoreHistories"
    ADD CONSTRAINT "FK_MerfitScoreHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Notifications"
    ADD CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "NutritionGoals"
    ADD CONSTRAINT "FK_NutritionGoals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "PersonalRecords"
    ADD CONSTRAINT "FK_PersonalRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_PersonalRecords_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_PersonalRecords_WorkoutSessions_WorkoutSessionId" FOREIGN KEY ("WorkoutSessionId") REFERENCES "WorkoutSessions" ("Id") ON DELETE SET NULL;

ALTER TABLE "Subscriptions"
    ADD CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Subscriptions_SubscriptionProducts_SubscriptionProductId" FOREIGN KEY ("SubscriptionProductId") REFERENCES "SubscriptionProducts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "SubscriptionPlanFeatures"
    ADD CONSTRAINT "FK_SubscriptionPlanFeatures_SubscriptionProductId" FOREIGN KEY ("SubscriptionProductId") REFERENCES "SubscriptionProducts" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_SubscriptionPlanFeatures_Features_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Features" ("Id") ON DELETE RESTRICT;

ALTER TABLE "SubscriptionTransactions"
    ADD CONSTRAINT "FK_SubscriptionTransactions_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id") ON DELETE RESTRICT;

ALTER TABLE "SupportTickets"
    ADD CONSTRAINT "FK_SupportTickets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "SupportTicketMessages"
    ADD CONSTRAINT "FK_SupportTicketMessages_SupportTickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "SupportTickets" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_SupportTicketMessages_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Translations"
    ADD CONSTRAINT "FK_Translations_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserAchievements"
    ADD CONSTRAINT "FK_UserAchievements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_UserAchievements_Achievements_AchievementId" FOREIGN KEY ("AchievementId") REFERENCES "Achievements" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserConsents"
    ADD CONSTRAINT "FK_UserConsents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_UserConsents_LegalDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "LegalDocuments" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserDevices"
    ADD CONSTRAINT "FK_UserDevices_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserEquipments"
    ADD CONSTRAINT "FK_UserEquipments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    ADD CONSTRAINT "FK_UserEquipments_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserGoals"
    ADD CONSTRAINT "FK_UserGoals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserNotificationSettings"
    ADD CONSTRAINT "FK_UserNotificationSettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserPreferences"
    ADD CONSTRAINT "FK_UserPreferences_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserPrivacySettings"
    ADD CONSTRAINT "FK_UserPrivacySettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserProfiles"
    ADD CONSTRAINT "FK_UserProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserRefreshTokens"
    ADD CONSTRAINT "FK_UserRefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserRewards"
    ADD CONSTRAINT "FK_UserRewards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_UserRewards_Rewards_RewardId" FOREIGN KEY ("RewardId") REFERENCES "Rewards" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_UserRewards_LeaderboardPeriods_LeaderboardPeriodId" FOREIGN KEY ("LeaderboardPeriodId") REFERENCES "LeaderboardPeriods" ("Id") ON DELETE SET NULL;

ALTER TABLE "UserStreaks"
    ADD CONSTRAINT "FK_UserStreaks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WaterLogs"
    ADD CONSTRAINT "FK_WaterLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Workouts"
    ADD CONSTRAINT "FK_Workouts_WorkoutCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "WorkoutCategories" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_Workouts_MuscleGroups_MuscleGroupId" FOREIGN KEY ("MuscleGroupId") REFERENCES "MuscleGroups" ("Id") ON DELETE SET NULL;

ALTER TABLE "WorkoutEquipments"
    ADD CONSTRAINT "FK_WorkoutEquipments_Workouts_WorkoutId" FOREIGN KEY ("WorkoutId") REFERENCES "Workouts" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_WorkoutEquipments_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutExercises"
    ADD CONSTRAINT "FK_WorkoutExercises_Workouts_WorkoutId" FOREIGN KEY ("WorkoutId") REFERENCES "Workouts" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_WorkoutExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutPlans"
    ADD CONSTRAINT "FK_WorkoutPlans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutPlanDays"
    ADD CONSTRAINT "FK_WorkoutPlanDays_WorkoutPlans_WorkoutPlanId" FOREIGN KEY ("WorkoutPlanId") REFERENCES "WorkoutPlans" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_WorkoutPlanDays_Workouts_WorkoutId" FOREIGN KEY ("WorkoutId") REFERENCES "Workouts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutSessions"
    ADD CONSTRAINT "FK_WorkoutSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_WorkoutSessions_Workouts_WorkoutId" FOREIGN KEY ("WorkoutId") REFERENCES "Workouts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutSessionExercises"
    ADD CONSTRAINT "FK_WorkoutSessionExercises_WorkoutSessions_WorkoutSessionId" FOREIGN KEY ("WorkoutSessionId") REFERENCES "WorkoutSessions" ("Id") ON DELETE RESTRICT,
    ADD CONSTRAINT "FK_WorkoutSessionExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES "Exercises" ("Id") ON DELETE RESTRICT;

ALTER TABLE "WorkoutSetLogs"
    ADD CONSTRAINT "FK_WorkoutSetLogs_WorkoutSessionExerciseId" FOREIGN KEY ("WorkoutSessionExerciseId") REFERENCES "WorkoutSessionExercises" ("Id") ON DELETE RESTRICT;

-- -----------------------------------------------------------------------------
-- 4) INDEKSLER
--    Postgres, foreign key kolonlarini otomatik indekslemez; EF Core migration'lari
--    her FK icin bir indeks olusturur, ayni davranis burada da uygulanmistir.
--    Ayrica UserEquipmentConfiguration'daki tekil (unique) indeks eklenmistir.
-- -----------------------------------------------------------------------------

CREATE INDEX "IX_AiGenerationRequests_UserId" ON "AiGenerationRequests" ("UserId");
CREATE INDEX "IX_AiGenerationResults_RequestId" ON "AiGenerationResults" ("RequestId");
CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
CREATE INDEX "IX_BodyMeasurements_UserId" ON "BodyMeasurements" ("UserId");
CREATE INDEX "IX_Exercises_PrimaryMuscleGroupId" ON "Exercises" ("PrimaryMuscleGroupId");
CREATE INDEX "IX_ExternalLogins_UserId" ON "ExternalLogins" ("UserId");
CREATE INDEX "IX_FAQs_CategoryId" ON "FAQs" ("CategoryId");
CREATE INDEX "IX_GoalHistories_UserId" ON "GoalHistories" ("UserId");
CREATE INDEX "IX_LeaderboardEntries_LeaderboardPeriodId" ON "LeaderboardEntries" ("LeaderboardPeriodId");
CREATE INDEX "IX_LeaderboardEntries_UserId" ON "LeaderboardEntries" ("UserId");
CREATE INDEX "IX_LeaderboardRewards_LeaderboardPeriodId" ON "LeaderboardRewards" ("LeaderboardPeriodId");
CREATE INDEX "IX_LeaderboardRewards_RewardId" ON "LeaderboardRewards" ("RewardId");
CREATE INDEX "IX_Meals_UserId" ON "Meals" ("UserId");
CREATE INDEX "IX_MealItems_MealId" ON "MealItems" ("MealId");
CREATE INDEX "IX_MealItems_FoodId" ON "MealItems" ("FoodId");
CREATE INDEX "IX_MerfitScores_UserId" ON "MerfitScores" ("UserId");
CREATE INDEX "IX_MerfitScoreBreakdowns_MerfitScoreId" ON "MerfitScoreBreakdowns" ("MerfitScoreId");
CREATE INDEX "IX_MerfitScoreHistories_UserId" ON "MerfitScoreHistories" ("UserId");
CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
CREATE INDEX "IX_NutritionGoals_UserId" ON "NutritionGoals" ("UserId");
CREATE INDEX "IX_PersonalRecords_UserId" ON "PersonalRecords" ("UserId");
CREATE INDEX "IX_PersonalRecords_ExerciseId" ON "PersonalRecords" ("ExerciseId");
CREATE INDEX "IX_PersonalRecords_WorkoutSessionId" ON "PersonalRecords" ("WorkoutSessionId");
CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");
CREATE INDEX "IX_Subscriptions_SubscriptionProductId" ON "Subscriptions" ("SubscriptionProductId");
CREATE INDEX "IX_SubscriptionPlanFeatures_FeatureId" ON "SubscriptionPlanFeatures" ("FeatureId");
CREATE INDEX "IX_SubscriptionTransactions_SubscriptionId" ON "SubscriptionTransactions" ("SubscriptionId");
CREATE INDEX "IX_SupportTickets_UserId" ON "SupportTickets" ("UserId");
CREATE INDEX "IX_SupportTicketMessages_TicketId" ON "SupportTicketMessages" ("TicketId");
CREATE INDEX "IX_SupportTicketMessages_SenderUserId" ON "SupportTicketMessages" ("SenderUserId");
CREATE INDEX "IX_Translations_LanguageId" ON "Translations" ("LanguageId");
CREATE INDEX "IX_UserAchievements_UserId" ON "UserAchievements" ("UserId");
CREATE INDEX "IX_UserAchievements_AchievementId" ON "UserAchievements" ("AchievementId");
CREATE INDEX "IX_UserConsents_UserId" ON "UserConsents" ("UserId");
CREATE INDEX "IX_UserConsents_DocumentId" ON "UserConsents" ("DocumentId");
CREATE INDEX "IX_UserDevices_UserId" ON "UserDevices" ("UserId");
CREATE INDEX "IX_UserEquipments_EquipmentId" ON "UserEquipments" ("EquipmentId");
CREATE UNIQUE INDEX "IX_UserEquipments_UserId_EquipmentId" ON "UserEquipments" ("UserId", "EquipmentId");
CREATE INDEX "IX_UserGoals_UserId" ON "UserGoals" ("UserId");
CREATE INDEX "IX_UserNotificationSettings_UserId" ON "UserNotificationSettings" ("UserId");
CREATE INDEX "IX_UserPreferences_UserId" ON "UserPreferences" ("UserId");
CREATE INDEX "IX_UserPrivacySettings_UserId" ON "UserPrivacySettings" ("UserId");
CREATE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");
CREATE INDEX "IX_UserRefreshTokens_UserId" ON "UserRefreshTokens" ("UserId");
CREATE INDEX "IX_UserRewards_UserId" ON "UserRewards" ("UserId");
CREATE INDEX "IX_UserRewards_RewardId" ON "UserRewards" ("RewardId");
CREATE INDEX "IX_UserRewards_LeaderboardPeriodId" ON "UserRewards" ("LeaderboardPeriodId");
CREATE INDEX "IX_UserStreaks_UserId" ON "UserStreaks" ("UserId");
CREATE INDEX "IX_WaterLogs_UserId" ON "WaterLogs" ("UserId");
CREATE INDEX "IX_Workouts_CategoryId" ON "Workouts" ("CategoryId");
CREATE INDEX "IX_Workouts_MuscleGroupId" ON "Workouts" ("MuscleGroupId");
CREATE INDEX "IX_WorkoutEquipments_EquipmentId" ON "WorkoutEquipments" ("EquipmentId");
CREATE INDEX "IX_WorkoutExercises_WorkoutId" ON "WorkoutExercises" ("WorkoutId");
CREATE INDEX "IX_WorkoutExercises_ExerciseId" ON "WorkoutExercises" ("ExerciseId");
CREATE INDEX "IX_WorkoutPlans_UserId" ON "WorkoutPlans" ("UserId");
CREATE INDEX "IX_WorkoutPlanDays_WorkoutPlanId" ON "WorkoutPlanDays" ("WorkoutPlanId");
CREATE INDEX "IX_WorkoutPlanDays_WorkoutId" ON "WorkoutPlanDays" ("WorkoutId");
CREATE INDEX "IX_WorkoutSessions_UserId" ON "WorkoutSessions" ("UserId");
CREATE INDEX "IX_WorkoutSessions_WorkoutId" ON "WorkoutSessions" ("WorkoutId");
CREATE INDEX "IX_WorkoutSessionExercises_WorkoutSessionId" ON "WorkoutSessionExercises" ("WorkoutSessionId");
CREATE INDEX "IX_WorkoutSessionExercises_ExerciseId" ON "WorkoutSessionExercises" ("ExerciseId");
CREATE INDEX "IX_WorkoutSetLogs_WorkoutSessionExerciseId" ON "WorkoutSetLogs" ("WorkoutSessionExerciseId");

-- =============================================================================
-- Bitis
-- =============================================================================
